services:
  app:
    depends_on:
      - $MYSQLDB_MASTER_HOST
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $JAVA_DEBUG_PORT:$JAVA_DEBUG_PORT
    environment:
      # looks like ssl=off is not sufficient, public key retrieval should be enabled (?)
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://$MYSQLDB_MASTER_HOST:$MYSQLDB_MASTER_PORT/$MYSQLDB_DATABASE?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true",
        "spring.datasource.replica-url"  : "jdbc:mysql://$MYSQLDB_REPLICA_HOST:$MYSQLDB_REPLICA1_PORT/$MYSQLDB_DATABASE?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD"
      }'
    stdin_open: true
    tty: true
  mysqldb:
    image: mysql:8.0.30
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_EXTERNAL_PORT:$MYSQLDB_MASTER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./db/my.cnf:/etc/my.cnf:ro
  websocket:
    build: ./highload-social-websocket
    restart: on-failure
    ports:
      - $WEBSOCKET_LOCAL_PORT:$WEBSOCKET_DOCKER_PORT
      - $WEBSOCKET_DEBUG_PORT:$JAVA_DEBUG_PORT

volumes:
  db:
  websocket: