services:
  mysqldb:
    image: mysql:8.0.30
    restart: unless-stopped
    env_file: ./.env
    # windows host fix
    command: >
      bash -c "
      chmod 644 /etc/my.cnf
      && /entrypoint.sh mysqld
      "
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./db/my.cnf:/etc/my.cnf
  app:
    depends_on:
      - mysqldb
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $JAVA_DEBUG_PORT:$JAVA_DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false&createDatabaseIfNotExist=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD"
      }'
    stdin_open: true
    tty: true

volumes:
  db: