services:
  app:
    depends_on:
      - $MYSQLDB_MASTER_HOST
    build: ./
    restart: on-failure
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $JAVA_DEBUG_PORT:$JAVA_DEBUG_PORT
    environment:
      # looks like ssl=off is not sufficient, public key retrieval should be enabled (?)
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://$MYSQLDB_MASTER_HOST:$MYSQLDB_MASTER_PORT/$MYSQLDB_DATABASE?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true",
        "spring.datasource.replica-url"  : "jdbc:mysql://$MYSQLDB_REPLICA_HOST:$MYSQLDB_REPLICA1_PORT/$MYSQLDB_DATABASE?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD"
      }'
    stdin_open: true
    tty: true
    networks:
      - percona-network

  percona-master:
    image: percona/percona-server:8.0
    env_file:
      - ".env"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_REPLICATION_USER: $MYSQLDB_USER
      MYSQL_REPLICATION_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    ports:
      - "3306:3306"
    networks:
      - percona-network
    volumes:
      - percona-master:/var/lib/mysql
      - ./db/my.cnf:/etc/my.cnf
  percona-replica-1:
    image: percona/percona-server:8.0
    env_file:
      - ".env"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_REPLICATION_USER: $MYSQLDB_USER
      MYSQL_REPLICATION_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_MASTER_HOST: percona-master
      MYSQL_MASTER_PORT: 3306
    ports:
      - "3307:3306"
    networks:
      - percona-network
    volumes:
      - percona-replica-1:/var/lib/mysql
      - ./db/my.cnf:/etc/my.cnf
  percona-replica-2:
    env_file:
      - ".env"
    image: percona/percona-server:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_REPLICATION_USER: $MYSQLDB_USER
      MYSQL_REPLICATION_PASSWORD: $MYSQLDB_ROOT_PASSWORD
      MYSQL_MASTER_HOST: percona-master
      MYSQL_MASTER_PORT: 3306
    ports:
      - "3308:3306"
    networks:
      - percona-network
    volumes:
      - percona-replica-2:/var/lib/mysql
      - ./db/my.cnf:/etc/my.cnf
volumes:
  percona-master:
  percona-replica-1:
  percona-replica-2:
networks:
  percona-network:
