app:
  queue:
    kafka-bootstrap: kafka-server:9092
    post-notification-topic: "post-notification"

management:
  endpoints:
    web:
      exposure:
        include: metrics,info,health,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http-server-requests: true
  endpoint:
    health:
      enabled: true
    prometheus:
      enabled: true
    info:
      enabled: true
spring:
  security:
    user:
      password: password
  liquibase:
    change-log: liquibase/changelog.sql
    enabled: true
  activemq:
    in-memory: true
    pool:
      enabled: false
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
logging:
  level:
    info:
      hauu:
        highloadsocial: DEBUG
